-- ============================================================
-- TrendPulse Supabase Schema (Complete & Fixed)
-- ============================================================

-- 0. Cleanup existing objects to avoid "Column does not exist" errors
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();
DROP TABLE IF EXISTS public.api_keys;
DROP TABLE IF EXISTS public.profiles;

-- 1. Create Profiles table (extension of auth.users)
-- This stores custom data like roles and regions for your users
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users(id) PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE NOT NULL,
  role TEXT DEFAULT 'user' CHECK (role IN ('user', 'admin')),
  region TEXT DEFAULT 'US',
  avatar_url TEXT,
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'banned', 'suspended')),
  joined_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Profiles Policies
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can update own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- 2. Create API Keys table
-- Stores the YouTube API keys that will be rotated in the dashboard
CREATE TABLE public.api_keys (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key_name TEXT NOT NULL,
  api_key TEXT NOT NULL,
  priority INTEGER DEFAULT 1,
  quota_limit INTEGER DEFAULT 10000,
  quota_used INTEGER DEFAULT 0,
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'warning', 'disabled')),
  last_used TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  created_by UUID REFERENCES auth.users(id)
);

-- Enable RLS on API Keys
ALTER TABLE public.api_keys ENABLE ROW LEVEL SECURITY;

-- API Keys Policies
-- Allow all logged-in users to see active keys for the analyzer to work
CREATE POLICY "Authenticated users can view active keys." ON public.api_keys
  FOR SELECT USING (auth.role() = 'authenticated' AND status != 'disabled');

-- Restrict full management (Add/Edit/Delete) to admins only
CREATE POLICY "Admins have full access to keys." ON public.api_keys
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.profiles 
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  );

-- 3. Automatic Profile Creation Trigger
-- Automatically creates a profile when a user signs up.
-- Also sets 'deepmagar505@gmail.com' as the system admin.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, username, email, role, status)
  VALUES (
    new.id, 
    split_part(new.email, '@', 1), -- Uses email prefix as starting username
    new.email, 
    CASE 
      WHEN new.email = 'deepmagar505@gmail.com' THEN 'admin' 
      ELSE 'user' 
    END,
    'active'
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 4. Enable Real-time (CRITICAL for Dashboard Sync)
-- This allows the dashboard to 'listen' for changes made by the admin
ALTER PUBLICATION supabase_realtime ADD TABLE public.api_keys;
